spring:
  dataspource:
    url: jdbc:mysql://localhost:3306/db/
    username: root
    password: password...................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
  application:
    name: sholaApp
server:
  port: 5020

