spring:
  application:
    name: postgresapp

  datasource:
    url: jdbc:postgresql://localhost:5432/studentdb
    username: postgres
    password: mypassword123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect